name: Test Node.js App

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      context: ./frontend/
      with:
        node-version: 18


    - name: Install dependencies
      run: npm ci

    - name: run container
      run: npm run lint

    - name: Run tests coverage
      run: npm run test:coverage
